services:
  nginx:
    image: nginx:latest
    restart: unless-stopped
    env_file:
      - ".env"
    environment:
      - DOLLAR=$$
    ports:
      - "${NGINX_HOST-0.0.0.0}:${NGINX_PORT-80}:80"
    networks:
      - titanic
    volumes:
      - "./web/nginx/templates:/etc/nginx/templates"
      - "./web/nginx/nginx.conf:/etc/nginx/nginx.conf"
    command: /bin/bash -c 'for template in /etc/nginx/templates/*.template; do envsubst < "$$template" > "/etc/nginx/conf.d/$$(basename "$$template" .template)"; done; nginx -g "daemon off;"'
