ALTER TABLE stats
    ADD COLUMN IF NOT EXISTS pp_vn real NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS pp_rx real NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS pp_ap real NOT NULL DEFAULT 0;

ALTER TABLE profile_rank_history
    ADD COLUMN IF NOT EXISTS pp_vn real NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS pp_rx real NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS pp_ap real NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS pp_vn_rank int NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS pp_rx_rank int NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS pp_ap_rank int NOT NULL DEFAULT 0;
